[workspace]
[package]
version = "0.1.0"
name = "method"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.1" }
zk_rust_io = { git = "https://github.com/yetanotherco/zkRust.git" }
